#!/bin/bash
LEGATO_ROOT="example" 
#Change This For Your System - This is where the legato directory is installed($LEGATO_ROOT")
UPDATE_FILE="example"
#Change This For Your System - This is the update file that should be sitting in the root directory of your legato app and is generated by the build system to be pushed to the mangOH. 
DEST_IP=192.168.2.2 
#This is the ip of your connected mangOH, which is by default set to 192.168.2.2 If you have changed this configuration on your mangOH, change this variable. 
pushd . 
cd $LEGATO_ROOT || exit
source ./bin/configlegatoenv 
popd
app install $UPDATE_FILE $DEST_IP
